KMP Algorithm.py
=> Create KMP Algorithm.py

ArmstrongNumber.cpp
C++ Code  To Check Armstrong Number
=> Armstrong Number

48 Rotate Image.cpp
Medium level problem on Leetcode
=> Create 48 Rotate Image.cpp

BinarySearchTreeTraversal.c
BinarySearchTreeTraversal using C.
=> added: BinarySearchTreeTraversal.c

number_pattern.py
interesting pyramid number pattern with python code.
=> added: number_pattern.py

binarytree_searchfunc.cpp
hey, I made a algorithm program to find a specific element from a binary tree also you can the address of the element
=> search function in binary tree

Rod_Cutting_Problem.cpp
Rod cutting problem using dynamic programming
=> Added Rod cutting problem

kadaneAlgorithm.cpp
Added code to find Maximum subarray sum in O(N) using Kadane's Algorithm.
=> Added kadaneAlgorithm.cpp

search_element_in_row_column_sorted_matrix.cpp
CPP Code to search an element in row-wise and column-wise sorted matrix
=> Created search_element_in_row_column_sorted_matrix.cpp

Pick_Toys.cpp
This picking toys problem is based on the sliding window technique.
=> Added Pick Toys Program

code rotate_matrix.cpp
C++ program to rotate a matrix in anti-clockwise direction
=> New code rotate_matrix.cpp

1.CheckSparseMatrix.cpp
=> check sparse matrix

Stack Using Array.cpp
=> Stack using array

Deletion in Linked List.cpp, README.md
=> Deleting Node in Linked List

2.Insertion in Linked List.cpp
=> Insertion in Linked List

java/StonePaperScissors
stone paper scissors game in java
=> StonePaperScissors-Game

cpp/kth_smallest_element.cpp
Signed-off-by: rithwik003 <amaraneni.rithwik@gmail.com>
=> Added kth_smallest_element.cpp file

cpp/palindrome_checker.cpp
Issue link : https://github.com/avichalsri/Resources/issues/158
=> Added palindrome_checker.cpp file

java/candyShop.java
- In the shop user will have the following options:
> *** Welcome to candy Shop *** <br />
To select an item,enter <br />
1 for Candy <br />
2 for Chips <br />
3 for Gum <br />
4 for Cookies <br />
9 for exit
- the shop will have limited amount of stock for each item and user can only buy upto the quantity the item is in stock 
- user receives a error message if the item is out of stock
- after selecting the item per item price and total amount to be deposited by user is shown
- user has to enter the amount
- if the amount entered is less, user is asked to enter the remaining amount 
- if the amount is more, user is returned the remaining amount
- when shop is exit remaining stock of items is shown along with the total amount collected
=> Add code for Candy Shop in Java

cpp/kmp_algorithm.cpp
C++ program for implementation of KMP pattern searching algorithm
=> Created kmp_algorithm.cpp

cpp/AggressiveCows.cpp
problem link:- [https://www.spoj.com/problems/AGGRCOW/](url)
=> Added Aggressive Cows cpp program

cpp/strong_number.cpp
Strong Numbers is a number in which the sum of the factorial of individual digits of the numbers is equal to the number itself.
=> Added strong_number.cpp file

cpp/reverse_integer.cpp
Signed-off-by: rithwik003 <amaraneni.rithwik@gmail.com>
=> Added reverse_integer.cpp

cpp/antiDiagonalPattern.cpp
added antiDiagonalPattern.cpp
Accept the PR with hactoberfest-accepted label.
=> added antiDiagonalPattern.cpp

cpp/Tug of War
Important BackTracking Questions
=> Create Tug of War

cpp/Jump Game II
This question enhance knowledge of DP ,Greedy
=> Create Jump Game II

cpp/LIS.cpp, cpp/lcs.cpp
=> LCS Algorithm

python/binary_search_using_function.py
#198 
Binary Search using functions in Python.
=> Binary Search using functions in Python. Closes#198

cpp/Insertion in LinkedList.cpp
Performing Insertion in LinkedList (Code and Algorithm)
=> Create Insertion in LinkedList.cpp

cpp/Deletion in LinkedList.cpp
Coding Deletion in LinkedList.
=> Create Deletion in LinkedList.cpp

cpp/Letter_Combinations_Phone_Number.cpp
Hi, I have provided the solution to the 
Letter Combinations of a Phone Number(Leetcode).
Hope you merge it.
waiting for the positive feedback.
=>  Letter_Combinations_of_a_Phone_Number

python/unique_paths.py
unique-paths (dp solution) famous problem included in blind 75
=> unique paths dp solution

c/countPrimes.c
This code counts the number of primes from 2 to given input range using sieve method.
=> Create countPrimes.c file

CONTRIBUTING.MD
Fixes #157 
Added a contributing markdown with all necessary steps and guidelines.  
Do let me know if anything needs to be changed.
=> CONTRIBUTING.md
